DATA:
  name : 'FashionMNIST'
  data_path: './dataset/'
  shape_in_c: 1
  shape_in_h: 28
  shape_in_w: 28
  num_classes: 10

MODEL:
  initial_filters: 8
  num_fc: 100
  dropout_rate: 0.2
  weight_path: "weights/weights_{}.pt"

TRAIN:
  epoch_num: 10
  batch_size: 512
  lr: 3e-4
  OPTIMIZER:
    NAME: 'Adam'

TEST:
  batch_size: 1000

IosForest:
  processing: 'PCA'
  contamination: 0.03

auto:
  feature_list: [ 'tsfel', 'PCA' ]
  beta_list: [ 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0 ]
  pixel_num_list: [ 1, 3, 5, 10, 20 ]

